<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('ins_ctc_recipes', function (Blueprint $table) {
            $table->id();
            $table->timestamps();

            $table->string('name')->unique();
            $table->string('og_rs');
            $table->decimal('std_min', 4, 2);
            $table->decimal('std_max', 4, 2);
            // std_mid removed - will be computed attribute
            $table->decimal('scale', 4, 2);
            $table->decimal('pfc_min', 4, 2);
            $table->decimal('pfc_max', 4, 2);

            $table->index('name');
            
            // Add constraint to ensure std_min <= std_max
            $table->index(['std_min', 'std_max']);
        });

        // Seed the recipe data (converted from legacy data)
        DB::table('ins_ctc_recipes')->insert([
            [
                'id' => 1,
                'name' => 'AF1 GS (BOTTOM)',
                'og_rs' => '1',
                'std_min' => 3.00,
                'std_max' => 3.10,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'AF1 GS (ONE COLOR)',
                'og_rs' => '1',
                'std_min' => 3.00,
                'std_max' => 3.10,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'AF1 GS (TWO COLOR)',
                'og_rs' => '1',
                'std_min' => 3.00,
                'std_max' => 3.10,
                'scale' => 1.00,
                'pfc_min' => 3.20,
                'pfc_max' => 3.40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'AF1 WS (BOTOM/CLEAR)',
                'og_rs' => '13',
                'std_min' => 3.60,
                'std_max' => 3.80,
                'scale' => 1.00,
                'pfc_min' => 3.60,
                'pfc_max' => 3.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'AF1 WS (LOGO)',
                'og_rs' => '7',
                'std_min' => 0.60,
                'std_max' => 0.80,
                'scale' => 1.00,
                'pfc_min' => 0.60,
                'pfc_max' => 0.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'AF1 WS (ONE COLOR)',
                'og_rs' => '11',
                'std_min' => 3.00,
                'std_max' => 3.10,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'AF1 WS (TWO COLOR)',
                'og_rs' => '7',
                'std_min' => 3.00,
                'std_max' => 3.10,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'AM 270 (CENTER)',
                'og_rs' => '1',
                'std_min' => 2.70,
                'std_max' => 2.90,
                'scale' => 1.00,
                'pfc_min' => 2.70,
                'pfc_max' => 2.90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'AM 270 (FOREFOOT)',
                'og_rs' => '1',
                'std_min' => 2.00,
                'std_max' => 2.20,
                'scale' => 1.00,
                'pfc_min' => 2.00,
                'pfc_max' => 2.20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'AM 270 (HEEL)',
                'og_rs' => '13',
                'std_min' => 2.80,
                'std_max' => 3.00,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'AM 270 (TOE)',
                'og_rs' => '1',
                'std_min' => 2.70,
                'std_max' => 2.80,
                'scale' => 1.00,
                'pfc_min' => 2.70,
                'pfc_max' => 2.90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'AM 95 (FF)',
                'og_rs' => '1',
                'std_min' => 2.70,
                'std_max' => 2.80,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'AM 95 (HEEL)',
                'og_rs' => '1',
                'std_min' => 2.80,
                'std_max' => 3.00,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'AM 95 (LOGO)',
                'og_rs' => '28',
                'std_min' => 0.60,
                'std_max' => 0.80,
                'scale' => 1.00,
                'pfc_min' => 0.60,
                'pfc_max' => 0.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'AM 95 (ONE COLOR)',
                'og_rs' => '1',
                'std_min' => 2.80,
                'std_max' => 3.00,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'AM TW (CENTER)',
                'og_rs' => '1',
                'std_min' => 3.40,
                'std_max' => 3.60,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'AM TW (HEEL POD)',
                'og_rs' => '1',
                'std_min' => 5.50,
                'std_max' => 5.70,
                'scale' => 1.00,
                'pfc_min' => 5.50,
                'pfc_max' => 5.70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'AM TW (ONE COLOR)',
                'og_rs' => '5',
                'std_min' => 3.20,
                'std_max' => 3.30,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'AM TW (TWO COLOR)',
                'og_rs' => '5',
                'std_min' => 3.20,
                'std_max' => 3.30,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'ALPHA 4',
                'og_rs' => '1',
                'std_min' => 2.60,
                'std_max' => 2.80,
                'scale' => 1.00,
                'pfc_min' => 2.60,
                'pfc_max' => 2.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'ALPHA 5',
                'og_rs' => '1',
                'std_min' => 3.20,
                'std_max' => 3.40,
                'scale' => 1.00,
                'pfc_min' => 3.20,
                'pfc_max' => 3.40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'ALPHA 5 (MARBLE)',
                'og_rs' => '1',
                'std_min' => 3.20,
                'std_max' => 3.40,
                'scale' => 1.00,
                'pfc_min' => 3.20,
                'pfc_max' => 3.40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'ALPHA 6',
                'og_rs' => '1',
                'std_min' => 2.70,
                'std_max' => 2.70,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'CBR (BOTTOM)',
                'og_rs' => '1',
                'std_min' => 3.60,
                'std_max' => 3.70,
                'scale' => 1.00,
                'pfc_min' => 3.80,
                'pfc_max' => 4.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'CBR (ONE COLOR)',
                'og_rs' => '1',
                'std_min' => 3.30,
                'std_max' => 3.30,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'CBR (TWO COLOR)',
                'og_rs' => '1',
                'std_min' => 3.30,
                'std_max' => 3.30,
                'scale' => 1.00,
                'pfc_min' => 3.40,
                'pfc_max' => 3.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'DWS 11',
                'og_rs' => '11',
                'std_min' => 2.30,
                'std_max' => 2.30,
                'scale' => 1.00,
                'pfc_min' => 2.40,
                'pfc_max' => 2.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'DWS 12 (ONE COLOR)',
                'og_rs' => '5',
                'std_min' => 2.10,
                'std_max' => 2.20,
                'scale' => 1.00,
                'pfc_min' => 2.20,
                'pfc_max' => 2.40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'DWS 12 (TWO COLOR FF)',
                'og_rs' => '5',
                'std_min' => 2.10,
                'std_max' => 2.20,
                'scale' => 1.00,
                'pfc_min' => 2.20,
                'pfc_max' => 2.40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'DWS 12 (TWO COLOR HEEL)',
                'og_rs' => '5',
                'std_min' => 2.60,
                'std_max' => 2.80,
                'scale' => 1.00,
                'pfc_min' => 2.60,
                'pfc_max' => 2.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'DWS 13',
                'og_rs' => '5',
                'std_min' => 1.90,
                'std_max' => 2.00,
                'scale' => 1.00,
                'pfc_min' => 2.00,
                'pfc_max' => 2.20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'INVIGOR',
                'og_rs' => '1',
                'std_min' => 4.10,
                'std_max' => 4.30,
                'scale' => 1.00,
                'pfc_min' => 5.00,
                'pfc_max' => 5.20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'PEG 37/38 (LATERAL)',
                'og_rs' => '2',
                'std_min' => 2.80,
                'std_max' => 3.00,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'PEG 37/38 (MEDIAL)',
                'og_rs' => '1',
                'std_min' => 2.40,
                'std_max' => 2.60,
                'scale' => 1.00,
                'pfc_min' => 2.40,
                'pfc_max' => 2.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'PEG 39/40 (LETERAL)',
                'og_rs' => '45',
                'std_min' => 2.30,
                'std_max' => 2.50,
                'scale' => 1.00,
                'pfc_min' => 2.30,
                'pfc_max' => 2.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'PEG 39/40 (MEDIAL)',
                'og_rs' => '45',
                'std_min' => 2.10,
                'std_max' => 2.30,
                'scale' => 1.00,
                'pfc_min' => 2.10,
                'pfc_max' => 2.30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'PEG 39/40 (ONE COLOR)',
                'og_rs' => '45',
                'std_min' => 2.30,
                'std_max' => 2.50,
                'scale' => 1.00,
                'pfc_min' => 2.30,
                'pfc_max' => 2.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'PEG 41 (LATERAL)',
                'og_rs' => '48',
                'std_min' => 2.40,
                'std_max' => 2.50,
                'scale' => 1.00,
                'pfc_min' => 2.60,
                'pfc_max' => 2.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'PEG 41 (MEDIAL)',
                'og_rs' => '48',
                'std_min' => 2.40,
                'std_max' => 2.50,
                'scale' => 1.00,
                'pfc_min' => 2.60,
                'pfc_max' => 2.80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'PHOENIX WAFFLE',
                'og_rs' => '1',
                'std_min' => 2.70,
                'std_max' => 2.70,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'QUEST 6',
                'og_rs' => '5',
                'std_min' => 2.30,
                'std_max' => 2.30,
                'scale' => 1.00,
                'pfc_min' => 2.40,
                'pfc_max' => 2.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'ALPHA 8 (FOREFOOT)',
                'og_rs' => '11',
                'std_min' => 2.60,
                'std_max' => 2.70,
                'scale' => 1.00,
                'pfc_min' => 2.80,
                'pfc_max' => 3.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'ALPHA 8 (HEEL)',
                'og_rs' => '11',
                'std_min' => 3.20,
                'std_max' => 3.30,
                'scale' => 1.00,
                'pfc_min' => 3.30,
                'pfc_max' => 3.50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ins_ctc_recipes');
    }
};